name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '45 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Configure bundle gem caching
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install ruby dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Update README
        env:
          AMAZON_USER: ${{ secrets.AMAZON_USER }}
          AMAZON_PASS: ${{ secrets.AMAZON_PASS }}
        run: |-
          bundle exec ruby index.rb
          cat README.md
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "chore: updated content" || exit 0
          git push
